### ISSUE TITLE
Unneeded timeout

### ISSUE THREAD

**Issue by maxtar** [amenzhinsky/iothub#12]
Hi.

In our project I've faced with 30s timeout when twin updates. But in transport setting and context I set 2 minutes. I've found the [following code](https://github.com/amenzhinsky/iothub/blob/bf15dfba85afc82b8015718577b0472bf08562f6/iotdevice/transport/mqtt/mqtt.go#L358). Is it really need this constant timeout?

**Comment by amenzhinsky** [comment]
Hi @maxtar, that makes sense to remove the timeout because we're passing ctx along with every request.
Would you like to create a MR?

**Comment by maxtar** [comment]
@amenzhinsky Do you mean PR? Or what is MR?

**Comment by amenzhinsky** [comment]
@maxtar sure PR, 
I'm mixing up github and gitlab terminology a bit.

**Comment by maxtar** [comment]
@amenzhinsky :) Ok, will create PR. :)

**Comment by amenzhinsky** [comment]
Closed via https://github.com/amenzhinsky/iothub/commit/bd88648ef55cea635ca3ae095a649c74299ff8a1

**Comment by maxtar** [comment]
Ups, sorry. :( Was vacation.
