### ISSUE TITLE
amqp:link:redirect error while using example code

### ISSUE THREAD

**Issue by midnightrun** [amenzhinsky/iothub#13]
Hi,
I was just using your example code for the service component and received an `amqp:link:redirect` error. In the documentation of AMQP this error is about the problem of not resolving the address to the container but everything in the response map look okay to me.

I just set up a fresh IoT Hub and created a device by hand and trying to run those examples on my local machine. The device code is working.

Any hints? :)

**Comment by amenzhinsky** [comment]
@midnightrun it looks like microsoft changed something, I'm looking into the problem.

**Comment by amenzhinsky** [comment]
Check out the latest tag https://github.com/amenzhinsky/iothub/releases/tag/v0.4.0 the error should be gone.
