### ISSUE TITLE
Support for IoT Hub query language for device and module twins, jobs, and message routing

### ISSUE THREAD

**Issue by lohmanndouglas** [amenzhinsky/iothub#33]
Is it possible to perform query requests now or is there any consideration to implement a query language feature?

[as described here](https://docs.microsoft.com/pt-br/azure/iot-hub/iot-hub-devguide-query-language)

I am figuring out a way to get modules and/or devices that are currently connected to your edgeHub. For that, I am doing GetModuleTwin requests for each device. With a query, I could save some requests. 

https://stackoverflow.com/questions/65014114/what-is-connected-client-count-on-azure-iot-edge-dashboard 

If there is no implementation for that and it is considered a useful feature, I would like to develop it :)

**Comment by amenzhinsky** [comment]
It's already implemented https://github.com/amenzhinsky/iothub/blob/445cd54636dd297745aecf9fc14a094c58ef3ab2/iotservice/client.go#L1122

**Comment by lohmanndouglas** [comment]
Thanks @amenzhinsky
