### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by lohmanndouglas** [amenzhinsky/iothub#35]
I have an application that was working since September 2020, but on January 13  it stopped :/

I am trying to 'SubscribeEvents' and I get this error "x509: certificate signed by unknown authority".

I can connect IoTservice.NewFromConnectionString(MyConnectionString), but when I subscribe to events I got this error. 

I would appreciate any help to configure it and make it works again.

**Comment by lohmanndouglas** [comment]
https://techcommunity.microsoft.com/t5/internet-of-things/azure-iot-tls-changes-are-coming-and-why-you-should-care/ba-p/1658456

**Comment by diegosz** [comment]
#37
