### ISSUE TITLE
Parsing the Request ID for direct methods fails

### ISSUE THREAD

**Issue by schuster-rainer** [amenzhinsky/iothub#40]
My device is setup using a Device Provisioning Service. I'm using ModuleClient to register a direct method. We get the auth from NewModuleFromEnvironment

On callback I get the following error while parsing the request id

ERROR parse error: $rid parse error: strconv.ParseInt: parsing "327358f7-b968-4f62-a8e5-8fb0cda316d4": invalid syntax.

When using the NewModuleFromConnectionString everything works fine so far. Any pointers on how to fix this with the DPS?

**Comment by amenzhinsky** [comment]
That's strange, I believe we had problems when rid suddenly switched from decimals to octals but if understand this correctly it's a uuid now.
