### ISSUE TITLE
Possible goroutine leaks in *Client.SendEvent()

### ISSUE THREAD

**Issue by greenhandatsjtu** [amenzhinsky/iothub#47]
Hi there, recently I found this SDK, and it's awesome! However, when I use `*Client.SendEvent` in `iotservice` package, I encountered a weird problem, **50 minutes** after calling this function, a log comes out as follows:
![image](https://user-images.githubusercontent.com/40566803/111938255-8ad0c580-8b04-11eb-90c8-fc4f44653d35.png)
```
2021/03/22 11:41:47 ERROR put token error: amqp: session closed
```
And I find a issue explaning this: https://github.com/amenzhinsky/iothub/issues/38#issuecomment-779242382 . As the comment explains, [`*Client.SendEvent`](https://github.com/amenzhinsky/iothub/blob/master/iotservice/client.go#L404~L430) will result in calling [`*Client.putTokenContinuously`](https://github.com/amenzhinsky/iothub/blob/master/iotservice/client.go#L150~L191):
```go
// putTokenContinuously in v0.7.0
func (c *Client) putTokenContinuously(ctx context.Context, conn *amqp.Client) error {
	const (
		tokenUpdateInterval = time.Hour

		// we need to update tokens before they expire to prevent disconnects
		// from azure, without interrupting the message flow
		tokenUpdateSpan = 10 * time.Minute
	)

	sess, err := conn.NewSession()
	if err != nil {
		return err
	}
	defer sess.Close(context.Background())

	if err := c.putToken(ctx, sess, tokenUpdateInterval); err != nil {
		return err
	}

	go func() {
		ticker := time.NewTimer(tokenUpdateInterval - tokenUpdateSpan)
		defer ticker.Stop()

		for {
			select {
			case <-ticker.C:
				if err := c.putToken(context.Background(), sess, tokenUpdateInterval); err != nil {
					c.logger.Errorf("put token error: %s", err)
					return
				}
				ticker.Reset(tokenUpdateInterval - tokenUpdateSpan)
				c.logger.Debugf("token updated")
			case <-c.done:
				return
			}
		}
	}()
	return nil
}

```
This function will start a new goroutine to `putToken` to update session token every 50 minutes (`tokenUpdateInterval` - `tokenUpdateSpan`). However, `defer sess.Close(context.Background())`  means that the session will be closed when `putTokenContinuously` returns. As a result, `putToken` called in the goroutine will always fail (which will log: `put token error: amqp: session closed`). **I notice that this problem has been fixed in recent commit** (though not released yet), but here's another question:

Each time I call the `*Client.SendEvent()`, it will **start a new session and start a goroutine to `putToken` every 50 minutes until the `Client` is closed**, which means **each time I send an event, a new endless goroutine is created** to `putToken` continuously, but all I need is just sending an event, after that, I don't need to maintain this session anymore (because next time I call `*Client.SendEvent()`, it will start another new session for me). What's more, as I have to call `*Client.SendEvent()` frequently, it could lead to a large number of goroutine leak.
My solution to this problem is that the `*Client.newSession()` called by `*Client.SendEvent()` don't call `putTokenContinuously`, it just call `putToken` and return the new session.

**Comment by amenzhinsky** [comment]
Hi,

Can you try the latest master, [this](https://github.com/amenzhinsky/iothub/commit/236b2a2e17365bea45261c09a248c66a3edf159f) should fix the error

**Comment by greenhandatsjtu** [comment]
That's it. Thank you!
