### ISSUE TITLE
Doesn't accept connection string without shared access key?

### ISSUE THREAD

**Issue by dangerousHobo** [amenzhinsky/iothub#66]
I'm trying to connect and it appears things are failing on the connection string. My connection string works with the C SDK.

This is the error I'm seeing:

`2022/10/10 17:51:44 SharedAccessKey is required`

My connection string:

`HostName=decog-iothub-eastus-###.azure-devices.net;DeviceId=mjohn-1;x509=true`

**Comment by amenzhinsky** [comment]
Hi, for now connection string parsing applies only to SAS authentication, if you need x509 try `iotdevice.NewFromX509Cert`.

Probably we can add x509 support when `x509=true`, but SDK needs to know where from it gets key/cert pair.

**Comment by dangerousHobo** [comment]
Thanks, `iotdevice.NewFromX509FromFile` worked for me.
The C SDK requires `OPTION_X509_CERT` and `OPTION_X509_PRIVATE_KEY` to be set if `x509=true` is used. Not sure there's a need for this in this SDK. I was just working on porting an existing application and missed the functions you mentioned.

Thanks for the help!
