### ISSUE TITLE
Help sending from service to device

### ISSUE THREAD

**Issue by jonathanface** [amenzhinsky/iothub#9]
Hi,

I've been using this library for almost a year and find it very useful. But I am confused about a panic state I get when trying to send from service to device via iotservice.SendEvent()

I get the following log whenever SendEvent gets called:
```
D connecting to SERVER_NAME.azure-devices.net
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x6fefe0]`
```
I presume I am not setting something correctly, but I'm not sure what.

Example code in the documentation would be helpful and appreciated.

Here is what I am doing:

```
var err error
iotServiceClient, err = iotservice.New(
	iotservice.WithConnectionString(IOT_SERVICE_CONNECTION_STRING),
        iotservice.WithLogger(common.NewLogWrapper(true)),
)	
if err != nil {
  log.Fatal("ioterr", err)
}
m := socketMessage{}
m.Command = "hello"
toBytes, err := json.Marshal(m)
if err != nil {
    log.Fatal("json", err)
}
iotServiceClient.SendEvent(context.Background(), "device123", toBytes)
```

**Comment by jonathanface** [comment]
I figured it out. I didn't realize that SendEvent requires the expiry time to be set.

For reference, changing the SendEvent method above to this resolved the issue.

```
iotServiceClient.SendEvent(ctx, "Buncher", toJSON,
  iotservice.WithSentExpiryTime(time.Now().Add(5*time.Second)),
)
```

**Comment by amenzhinsky** [comment]
@jonathanface thanks for reporting the issue, this is definitely a bug, already fixed it in master: https://github.com/amenzhinsky/iothub/commit/fb38f4d4c9fb50af19d350a96199bf06b3869d29
